operation: predict

defaults:
  source: /mnt/data/ent_cv/raw/20251113_02
  weights: /mnt/data/ent_cv/models/yolo26x_20260227_124156/weights/best.pt

  # optional (defaults shown)
  conf: 0.647
  iou: 0.7
  imgsz: 640
  device: "0"
  save: true
  save_conf: true
  save_txt: true
  save_json: true
  save_frames: true
  onnx: false
  # output_dir:   # defaults to predictions/<source_stem>
  # suffix:       # appended to output dir name (e.g. "v2" → predictions/<source_stem>_v2)
  overwrite: false

runs:
  - source: /mnt/data/ent_cv/raw/20251113_02/
  # - source: /mnt/data/ent_cv/raw/20251113_02
  # - source: /mnt/data/ent_cv/raw/20251124_01
  # - source: /mnt/data/ent_cv/raw/20251204_01
  # - source: /mnt/data/ent_cv/raw/20251208_01
  # - source: /mnt/data/ent_cv/raw/20251208_02
  # - source: /mnt/data/ent_cv/raw/20251210_02
  # - source: /mnt/data/ent_cv/raw/20251210_03
  # - source: /mnt/data/ent_cv/raw/20251217_02
  # - source: /mnt/data/ent_cv/raw/20251217_03
  # - source: /mnt/data/ent_cv/raw/20251218_02
  # - source: /mnt/data/ent_cv/raw/20260128_01
  # - source: /mnt/data/ent_cv/raw/20260205_01
  # - source: /mnt/data/ent_cv/raw/20260205_03
