# train config
# Usage: uv run -m ent_cv.modeling.train

# required
data: /mnt/data/ent_cv/datasets/combined_new/data_with_val.yaml
model: yolo26x

# optional
epochs: 200
batch: -1
imgsz: 1024
rect: true
scale: 0.0
device: 0
