# val config
# Usage: uv run -m ent_cv.modeling.val

# required
weights: /mnt/data/ent_cv/models/v1/weights/best.pt
data: /mnt/data/ent_cv/datasets/combined_new/data_with_val.yaml

# optional (defaults shown)
# conf: 0.001
# iou: 0.6
device: "0"
# half: false
split: val       # "val", "test", or "train"
# save_json: true
verbose: true
# imgsz:
# batch:
# name: 