project_name: "ENT_CV"
# project_description: ""

data_root: "data"
target_subdir: "raw"

label_file: "ent_cv/labels.json"

# https://cvat.jaehho.com/api/docs/#tag/tasks/operation/tasks_create_data
# task_prefix: ""
image_quality: 70
frame_step: 360

# use_zip_chunks: false
# use_cache: false
# copy_data: true
# sorting_method: "natural"

# Auto Annotation
auto_annotate:
  # If this list is present and not empty, the script will ONLY process these tasks.
  # If you want to process the whole project, comment this list out or leave it empty [].
  task_ids: [1] 
  
  model_name: "ent_cv"
  threshold: 60
  cleanup: true
  quality: "original"